<?php

namespace App\Models;

use App\Traits\HasQuota;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 * User Model
 *
 * Represents a user in the ReplyStack platform.
 * Users can belong to an organization and have quotas based on their plan.
 *
 * @property int $id
 * @property string $email
 * @property string $password
 * @property string|null $name
 * @property string $plan
 * @property int $daily_quota
 * @property int $monthly_quota
 * @property int $quota_used_today
 * @property int $quota_used_month
 * @property \Carbon\Carbon|null $quota_reset_at
 * @property string|null $stripe_customer_id
 * @property string|null $stripe_subscription_id
 * @property int|null $organization_id
 * @property \Carbon\Carbon|null $email_verified_at
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 *
 * @property-read Organization|null $organization
 * @property-read \Illuminate\Database\Eloquent\Collection|Location[] $locations
 * @property-read \Illuminate\Database\Eloquent\Collection|Response[] $responses
 * @property-read int|string $quota_remaining
 * @property-read int|string $quota_limit
 * @property-read int $quota_used
 */
class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasApiTokens, HasFactory, HasQuota, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'plan',
        'daily_quota',
        'monthly_quota',
        'quota_used_today',
        'quota_used_month',
        'quota_reset_at',
        'stripe_customer_id',
        'stripe_subscription_id',
        'organization_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'stripe_customer_id',
        'stripe_subscription_id',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var list<string>
     */
    protected $appends = [
        'quota_remaining',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'quota_reset_at' => 'datetime',
            'password' => 'hashed',
            'daily_quota' => 'integer',
            'monthly_quota' => 'integer',
            'quota_used_today' => 'integer',
            'quota_used_month' => 'integer',
        ];
    }

    /**
     * Get the organization that the user belongs to.
     *
     * @return BelongsTo<Organization, User>
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }

    /**
     * Get the locations owned by the user.
     *
     * @return HasMany<Location>
     */
    public function locations(): HasMany
    {
        return $this->hasMany(Location::class);
    }

    /**
     * Get the responses generated by the user.
     *
     * @return HasMany<Response>
     */
    public function responses(): HasMany
    {
        return $this->hasMany(Response::class);
    }

    /**
     * Get the templates created by the user.
     *
     * @return HasMany<Template>
     */
    public function templates(): HasMany
    {
        return $this->hasMany(Template::class);
    }

    /**
     * Get the organizations owned by the user.
     *
     * @return HasMany<Organization>
     */
    public function ownedOrganizations(): HasMany
    {
        return $this->hasMany(Organization::class, 'owner_id');
    }

    /**
     * Check if the user is the owner of their organization.
     *
     * @return bool
     */
    public function isOrganizationOwner(): bool
    {
        if (!$this->organization_id) {
            return false;
        }

        return $this->organization?->owner_id === $this->id;
    }

    /**
     * Check if the user has a paid plan.
     *
     * @return bool
     */
    public function hasPaidPlan(): bool
    {
        return in_array($this->plan, ['starter', 'pro', 'business', 'enterprise']);
    }

    /**
     * Check if the user has a specific plan or higher.
     *
     * @param string $plan The minimum plan to check for
     * @return bool
     */
    public function hasPlanOrHigher(string $plan): bool
    {
        $planOrder = ['free' => 0, 'starter' => 1, 'pro' => 2, 'business' => 3, 'enterprise' => 4];

        return ($planOrder[$this->plan] ?? 0) >= ($planOrder[$plan] ?? 0);
    }

    /**
     * Check if the user can add a new location based on their plan.
     *
     * @return bool
     */
    public function canAddLocation(): bool
    {
        $currentCount = $this->locations()->count();

        return $currentCount < $this->getMaxLocations();
    }

    /**
     * Get the maximum number of locations allowed for the user's plan.
     *
     * @return int
     */
    public function getMaxLocations(): int
    {
        return match ($this->plan) {
            'business', 'enterprise' => 10,
            default => 1,
        };
    }

    /**
     * Get the user's Stripe customer ID, creating one if it doesn't exist.
     *
     * @return string|null
     */
    public function getOrCreateStripeCustomerId(): ?string
    {
        if ($this->stripe_customer_id) {
            return $this->stripe_customer_id;
        }

        // This would integrate with Stripe - placeholder for now
        return null;
    }

    /**
     * Scope a query to only include users with a specific plan.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $plan
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWithPlan($query, string $plan)
    {
        return $query->where('plan', $plan);
    }

    /**
     * Scope a query to only include users in a specific organization.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param int $organizationId
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeInOrganization($query, int $organizationId)
    {
        return $query->where('organization_id', $organizationId);
    }
}
