@extends('legal.layouts.legal')

@section('title', 'Terms of Use')
@section('link_legal', 'Legal Notice')
@section('link_terms', 'Terms of Use')
@section('link_sales', 'Terms of Sale')
@section('link_privacy', 'Privacy Policy')
@section('link_cookies', 'Cookie Policy')

@section('content')
<h1>Terms of Use</h1>
<p class="last-updated">{{ $translations['lastUpdated'] }}: {{ $lastUpdatedDate }}</p>

<div class="highlight-box">
    <strong>Important:</strong> By using ReplyStack, you agree to these Terms of Use. Please read them carefully before using our services.
</div>

<h2>1. Definitions</h2>
<ul>
    <li><strong>"ReplyStack"</strong>, <strong>"we"</strong>, <strong>"us"</strong>, <strong>"our"</strong>: {{ $companyName }}, a {{ $companyForm }} registered under Moroccan law, ICE {{ $companyId }}.</li>
    <li><strong>"Service"</strong>: The ReplyStack platform including the web application, dashboard, browser extension, and all related features.</li>
    <li><strong>"User"</strong>, <strong>"you"</strong>, <strong>"your"</strong>: Any individual or entity using the Service.</li>
    <li><strong>"Content"</strong>: All text, data, information, reviews, responses, and materials uploaded, generated, or processed through the Service.</li>
    <li><strong>"AI-Generated Content"</strong>: Responses and text generated by the artificial intelligence system integrated into ReplyStack.</li>
</ul>

<h2>2. Acceptance of Terms</h2>
<p>By creating an account, installing the browser extension, or using any part of the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use.</p>
<p>If you do not agree to these terms, you must not use the Service.</p>

<h2>3. Service Description</h2>
<p>ReplyStack provides:</p>
<ul>
    <li>AI-powered generation of responses to customer reviews</li>
    <li>A browser extension for Chrome and Firefox to generate responses directly on review platforms</li>
    <li>A web dashboard to manage responses, view analytics, and configure preferences</li>
    <li>Integration with third-party review platforms (Google Business, TripAdvisor, etc.)</li>
</ul>

<h2>4. Account Registration</h2>

<h3>4.1 Eligibility</h3>
<p>You must be at least 18 years old and have the legal capacity to enter into contracts to use the Service. By using ReplyStack, you represent and warrant that you meet these requirements.</p>

<h3>4.2 Account Information</h3>
<p>You agree to:</p>
<ul>
    <li>Provide accurate, current, and complete information during registration</li>
    <li>Maintain and promptly update your account information</li>
    <li>Keep your password secure and confidential</li>
    <li>Notify us immediately of any unauthorized use of your account</li>
</ul>

<h3>4.3 Account Responsibility</h3>
<p>You are responsible for all activities that occur under your account. We are not liable for any loss or damage arising from unauthorized use of your account.</p>

<h2>5. Acceptable Use</h2>

<h3>5.1 Permitted Uses</h3>
<p>You may use the Service to:</p>
<ul>
    <li>Generate AI-powered responses to legitimate customer reviews for your business</li>
    <li>Manage and track review responses</li>
    <li>Access analytics and insights about your review management</li>
</ul>

<h3>5.2 Prohibited Uses</h3>
<p>You agree NOT to:</p>
<ul>
    <li>Use the Service for any illegal purpose or in violation of any laws</li>
    <li>Generate responses that are defamatory, abusive, harassing, or discriminatory</li>
    <li>Use the Service to deceive consumers or publish false reviews</li>
    <li>Attempt to reverse-engineer, decompile, or disassemble the Service</li>
    <li>Use automated systems (bots, scrapers) to access the Service beyond normal usage</li>
    <li>Share your account credentials with third parties</li>
    <li>Resell, redistribute, or sublicense access to the Service</li>
    <li>Interfere with or disrupt the Service or servers</li>
    <li>Circumvent any usage limits or quotas</li>
    <li>Use the Service to compete with ReplyStack</li>
</ul>

<h2>6. AI-Generated Content</h2>

<h3>6.1 Nature of AI Responses</h3>
<p>The responses generated by ReplyStack are produced by artificial intelligence. While we strive for accuracy and quality:</p>
<ul>
    <li>AI-generated content may contain errors or inaccuracies</li>
    <li>Responses are suggestions and should be reviewed before publishing</li>
    <li>You are solely responsible for reviewing and approving any content before publication</li>
</ul>

<h3>6.2 User Responsibility</h3>
<p>You acknowledge and agree that:</p>
<ul>
    <li>You will review all AI-generated responses before publishing</li>
    <li>You are responsible for the accuracy and appropriateness of published responses</li>
    <li>ReplyStack is not responsible for any consequences arising from published responses</li>
    <li>You will not hold ReplyStack liable for any damages resulting from AI-generated content</li>
</ul>

<h2>7. Intellectual Property</h2>

<h3>7.1 ReplyStack Property</h3>
<p>The Service, including its design, features, code, and all related intellectual property, is owned by {{ $companyName }}. You are granted a limited, non-exclusive, non-transferable license to use the Service in accordance with these Terms.</p>

<h3>7.2 Your Content</h3>
<p>You retain ownership of your original content. By using the Service, you grant us a limited license to process your content solely for providing the Service.</p>

<h3>7.3 AI-Generated Responses</h3>
<p>You may use AI-generated responses for your business purposes. We do not claim ownership over AI-generated content created for your use.</p>

<h2>8. Third-Party Services</h2>

<h3>8.1 Platform Integration</h3>
<p>The Service integrates with third-party platforms (Google, Facebook, TripAdvisor, etc.). Your use of these integrations is also subject to the terms of service of those platforms.</p>

<h3>8.2 No Endorsement</h3>
<p>Integration with third-party services does not constitute endorsement by ReplyStack. We are not responsible for the availability, accuracy, or policies of third-party services.</p>

<h2>9. Service Availability</h2>

<h3>9.1 Uptime</h3>
<p>We strive to maintain high availability of the Service but do not guarantee uninterrupted access. The Service may be temporarily unavailable due to:</p>
<ul>
    <li>Scheduled maintenance (we will provide advance notice when possible)</li>
    <li>Emergency maintenance or updates</li>
    <li>Factors beyond our control (internet outages, third-party service issues)</li>
</ul>

<h3>9.2 Modifications</h3>
<p>We reserve the right to modify, suspend, or discontinue any part of the Service at any time. We will provide reasonable notice for material changes.</p>

<h2>10. Limitation of Liability</h2>

<div class="warning-box">
    <p><strong>Important:</strong> To the maximum extent permitted by law:</p>
    <ul>
        <li>The Service is provided "AS IS" and "AS AVAILABLE" without warranties of any kind</li>
        <li>We disclaim all implied warranties, including merchantability and fitness for a particular purpose</li>
        <li>We are not liable for any indirect, incidental, special, consequential, or punitive damages</li>
        <li>Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim</li>
    </ul>
</div>

<h2>11. Indemnification</h2>
<p>You agree to indemnify, defend, and hold harmless ReplyStack, its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from:</p>
<ul>
    <li>Your use of the Service</li>
    <li>Your violation of these Terms</li>
    <li>Your violation of any third-party rights</li>
    <li>Content you publish using the Service</li>
</ul>

<h2>12. Termination</h2>

<h3>12.1 Termination by You</h3>
<p>You may terminate your account at any time by contacting us or using the account settings. Upon termination, your right to use the Service will immediately cease.</p>

<h3>12.2 Termination by Us</h3>
<p>We may suspend or terminate your account if:</p>
<ul>
    <li>You violate these Terms of Use</li>
    <li>Your use poses a security risk</li>
    <li>You fail to pay applicable fees</li>
    <li>Required by law or legal process</li>
</ul>

<h3>12.3 Effect of Termination</h3>
<p>Upon termination, all licenses granted to you will terminate, and you must cease using the Service. We may delete your data in accordance with our Privacy Policy.</p>

<h2>13. Governing Law and Disputes</h2>
<p>These Terms are governed by the laws of the Kingdom of Morocco. Any disputes arising from these Terms or your use of the Service shall be subject to the exclusive jurisdiction of the courts of Marrakech, Morocco.</p>

<h2>14. Changes to Terms</h2>
<p>We may update these Terms from time to time. We will:</p>
<ul>
    <li>Notify you of material changes by email</li>
    <li>Provide at least 30 days notice before changes take effect</li>
    <li>Update the "Last Updated" date at the top of this page</li>
</ul>
<p>Continued use of the Service after changes take effect constitutes acceptance of the new Terms.</p>

<h2>15. Miscellaneous</h2>

<h3>15.1 Entire Agreement</h3>
<p>These Terms, together with our Privacy Policy and Terms of Sale, constitute the entire agreement between you and ReplyStack.</p>

<h3>15.2 Severability</h3>
<p>If any provision of these Terms is found invalid or unenforceable, the remaining provisions will continue in full force and effect.</p>

<h3>15.3 Waiver</h3>
<p>Our failure to enforce any right or provision of these Terms does not constitute a waiver of such right or provision.</p>

<h3>15.4 Assignment</h3>
<p>You may not assign or transfer these Terms without our prior written consent. We may assign our rights and obligations without restriction.</p>

<h2>16. Contact</h2>
<p>For questions about these Terms of Use:</p>
<ul>
    <li><strong>Email:</strong> <a href="mailto:{{ $contactEmail }}">{{ $contactEmail }}</a></li>
    <li><strong>Address:</strong> {{ $companyName }}, {{ $companyAddress }}</li>
</ul>
@endsection
