@extends('legal.layouts.legal')

@section('title', 'Legal Notice')
@section('link_legal', 'Legal Notice')
@section('link_terms', 'Terms of Use')
@section('link_sales', 'Terms of Sale')
@section('link_privacy', 'Privacy Policy')
@section('link_cookies', 'Cookie Policy')

@section('content')
<h1>Legal Notice</h1>
<p class="last-updated">{{ $translations['lastUpdated'] }}: {{ $lastUpdatedDate }}</p>

<h2>1. Website Publisher</h2>
<p>This website is published by:</p>
<ul>
    <li><strong>Company Name:</strong> {{ $companyName }}</li>
    <li><strong>Commercial Name:</strong> {{ $commercialName }}</li>
    <li><strong>Legal Form:</strong> {{ $companyForm }} (Société Anonyme under Moroccan Law)</li>
    <li><strong>ICE (Identifiant Commun de l'Entreprise):</strong> {{ $companyId }}</li>
    <li><strong>Registered Office:</strong> {{ $companyAddress }}</li>
    <li><strong>Email:</strong> <a href="mailto:{{ $contactEmail }}">{{ $contactEmail }}</a></li>
</ul>

<h2>2. Publication Director</h2>
<p>The Publication Director responsible for the content of this website is:</p>
<ul>
    <li><strong>Name:</strong> {{ $directorName }}</li>
    <li><strong>Position:</strong> {{ $directorTitle }}</li>
    <li><strong>Contact:</strong> <a href="mailto:{{ $contactEmail }}">{{ $contactEmail }}</a></li>
</ul>

<h2>3. Hosting</h2>
<p>This website is hosted by:</p>

<h3>3.1 API (Backend)</h3>
<ul>
    <li><strong>Host:</strong> Railway Corporation</li>
    <li><strong>Address:</strong> 548 Market St, PMB 65883, San Francisco, CA 94104, USA</li>
    <li><strong>Website:</strong> <a href="https://railway.app" target="_blank">railway.app</a></li>
</ul>

<h3>3.2 Web Application (Frontend)</h3>
<ul>
    <li><strong>Host:</strong> Vercel Inc.</li>
    <li><strong>Address:</strong> 340 S Lemon Ave #4133, Walnut, CA 91789, USA</li>
    <li><strong>Website:</strong> <a href="https://vercel.com" target="_blank">vercel.com</a></li>
</ul>

<h2>4. Intellectual Property</h2>

<h3>4.1 Trademarks</h3>
<p>ReplyStack® and the ReplyStack logo are trademarks of {{ $companyName }}. Any unauthorized reproduction, imitation, or use of these trademarks is prohibited.</p>

<h3>4.2 Website Content</h3>
<p>All content on this website (texts, images, graphics, logos, icons, sounds, software, etc.) is the exclusive property of {{ $companyName }} or its partners and is protected by intellectual property laws.</p>
<p>Any reproduction, representation, modification, publication, or adaptation of all or part of the elements of the site is prohibited without prior written authorization from {{ $companyName }}.</p>

<h3>4.3 Software</h3>
<p>The ReplyStack platform, including the web application and browser extension, is proprietary software. The source code, algorithms, and underlying technology are protected by intellectual property rights.</p>

<h2>5. User-Generated Content</h2>
<p>Users may generate content through the Service (such as AI-generated responses). Users retain rights to their original content but grant {{ $companyName }} a license to process such content for service delivery purposes as described in our Terms of Use.</p>

<h2>6. Limitation of Liability</h2>

<h3>6.1 Website Information</h3>
<p>{{ $companyName }} endeavors to ensure that the information available on this website is accurate and up-to-date. However, we cannot guarantee the accuracy, completeness, or timeliness of the information provided. We reserve the right to modify the content at any time without notice.</p>

<h3>6.2 External Links</h3>
<p>This website may contain links to third-party websites. {{ $companyName }} has no control over the content of these external sites and disclaims all responsibility for their content, including any products, services, or information they may offer.</p>

<h3>6.3 AI-Generated Content</h3>
<p>The responses generated by ReplyStack's artificial intelligence are suggestions only. Users are solely responsible for reviewing and approving any content before publication. {{ $companyName }} is not liable for the consequences of publishing AI-generated content.</p>

<h2>7. Applicable Law</h2>
<p>This website and its content are governed by the laws of the Kingdom of Morocco. Any dispute relating to the use of this website shall be subject to the exclusive jurisdiction of the courts of Marrakech, Morocco.</p>

<h2>8. Data Protection</h2>
<p>Personal data collected through this website is processed in accordance with applicable data protection laws, including:</p>
<ul>
    <li>Moroccan Law 09-08 on the protection of individuals with regard to the processing of personal data</li>
    <li>EU General Data Protection Regulation (GDPR) for European users</li>
    <li>California Consumer Privacy Act (CCPA) for California residents</li>
    <li>Brazilian General Data Protection Law (LGPD) for Brazilian users</li>
</ul>
<p>For more information, please refer to our <a href="/privacy?lang=en">Privacy Policy</a>.</p>

<h2>9. Accessibility</h2>
<p>We strive to make our website accessible to all users. If you encounter any accessibility issues, please contact us at <a href="mailto:{{ $contactEmail }}">{{ $contactEmail }}</a>.</p>

<h2>10. Credits</h2>
<p>Website design and development: {{ $companyName }}</p>

<h2>11. Contact</h2>
<p>For any questions regarding this legal notice:</p>
<ul>
    <li><strong>Email:</strong> <a href="mailto:{{ $contactEmail }}">{{ $contactEmail }}</a></li>
    <li><strong>Address:</strong> {{ $companyName }}, {{ $companyAddress }}</li>
</ul>
@endsection
